# Generated by Django 4.2.1 on 2023-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='year',
            field=models.TextField(default=4, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
