# Generated by Django 4.2.1 on 2023-06-08 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Время'),
        ),
    ]
