# Generated by Django 4.2.1 on 2023-06-09 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
                ('anons', models.CharField(max_length=50, verbose_name='Level')),
                ('full_text', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
