# Generated by Django 4.2.1 on 2023-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.RemoveField(
            model_name='state',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='state',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='state',
            name='title',
        ),
        migrations.AddField(
            model_name='state',
            name='score1',
            field=models.TextField(default='DEFAULT VALUE', verbose_name='1score'),
        ),
        migrations.AddField(
            model_name='state',
            name='score2',
            field=models.TextField(default='DEFAULT VALUE', verbose_name='2score'),
        ),
        migrations.AddField(
            model_name='state',
            name='team1',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, verbose_name='1team'),
        ),
        migrations.AddField(
            model_name='state',
            name='team2',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, verbose_name='2team'),
        ),
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
