# Generated by Django 4.2.1 on 2023-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0002_alter_state_options_remove_state_anons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='map',
            field=models.TextField(default='DEFAULT VALUE', verbose_name='2score'),
        ),
    ]
