# Generated by Django 4.2.1 on 2023-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0003_state_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='map',
            field=models.TextField(default='', verbose_name='2score'),
        ),
        migrations.AlterField(
            model_name='state',
            name='score1',
            field=models.TextField(default='', verbose_name='1score'),
        ),
        migrations.AlterField(
            model_name='state',
            name='score2',
            field=models.TextField(default='', verbose_name='2score'),
        ),
        migrations.AlterField(
            model_name='state',
            name='team1',
            field=models.CharField(default='', max_length=50, verbose_name='1team'),
        ),
        migrations.AlterField(
            model_name='state',
            name='team2',
            field=models.CharField(default='', max_length=50, verbose_name='2team'),
        ),
    ]
