# Generated by Django 4.2.1 on 2023-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0004_alter_state_map_alter_state_score1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='map',
            field=models.TextField(default='', verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='state',
            name='score1',
            field=models.CharField(default='', max_length=50, verbose_name='score1'),
        ),
        migrations.AlterField(
            model_name='state',
            name='score2',
            field=models.CharField(default='', max_length=50, verbose_name='score2'),
        ),
    ]
